#!/bin/rc

CC='/usr/bin/gcc'
CXX='/usr/bin/g++'

CFLAGS='-march=x86-64 -pipe -Os -fstack-protector-strong -fstack-clash-protection -Wl,-rpath=/usr/lib64 '
RUSTFLAGS='-C target-cpu=x86-64 -C opt-level=s -C debuginfo=0 -C panic=abort'
MAKEOPTS=-j5

PREFIX='/usr'
LIBDIR=$PREFIX/lib64
dirflags=('localstatedir=/var' 'sysconfdir=/etc' 'libdir='$LIBDIR)

# list of dbs to concatenate as part of the total db
db=/usr/nullpkg/db/^(base.db lib.db nox.db gtk.db qt.db xfce.db gpg.db)
