#!/bin/rc

CC='/usr/bin/gcc'
CXX='/usr/bin/g++'

CFLAGS='-march=x86-64 -pipe -Os -fstack-protector-strong -fstack-clash-protection'
RUSTFLAGS='-C target-cpu=x86-64 -C opt-level=s -C debuginfo=0 -C panic=abort'
MAKEOPTS=-j5

PREFIX='/usr'
SBINDIR='/usr/sbin'
LIBDIR=$PREFIX/lib64

# default flags
dirflags=('localstatedir=/var' 'sysconfdir=/etc' 'libdir='$LIBDIR 'disable-static')

# list of dbs to concatenate as part of the total db
db=/usr/nullpkg/db/^(base.db lib.db misc.db xfce.db)

# other env vars
path=(/usr/sbin /usr/bin /sbin /bin)
CXXFLAGS=$CFLAGS
SOURCE_DATE_EPOCH=1000000000
KBUILD_BUILD_TIMESTAMP=1000000000
FORCE_UNSAFE_CONFIGURE=1
