#!/usr/bin/env rc

CC='/usr/bin/gcc'
CXX='/usr/bin/g++'
CFLAGS=( \
    '-march=x86-64' \
    '-pipe' \
    '-Os' \
    '-fstack-protector-strong' \
    '-fstack-clash-protection' \
)
RUSTFLAGS='-C'^( \
    'opt-level=s' \
    'debuginfo=0' \
    'panic=abort' \
)
PREFIX='/usr'
MAKEOPTS='-j5'
buildtype='release'

# list of dbs to concatenate as part of the total db
db=/usr/slackage/^(system.db db/^(gnu.db qt.db rust.db xfce.db))

FORCE_UNSAFE_CONFIGURE=1
PKG_CONFIG_PATH=/usr/lib/pkgconfig
LD_LIBRARY_PATH=/usr/lib
